# Generated by Django 5.0.3 on 2024-03-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-id',)},
        ),
    ]
